language: python

python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: "usil-ogranization"
script:
  - pytest -v --cov --cov-report=xml --cov-report=html
  - behave ./test_aceptance/
  - sonar-scanner